name: Release

on:
  pull_request:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

jobs:
  release-demo:
    name: Release Demo APK to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Store STATE
        id: store
        run: |
          echo "::set-output name=proPath::$(find app -name '*.pro')"
      - name: Echo output
        run: |
          echo "${{ steps.store.outputs.proPath }}"
#      - name: Build demo APK
#        run: |
#          ./gradlew clean assemble --stacktrace
#      - name: Find
#        run: |
#          find . -name 'CircularSeekBar-demo-*-release.apk'
#      - name: Store output APK to STATE
#        id: output
#        run: |
#          echo "::set-output name=apkPath::$(find . -name 'CircularSeekBar-demo-*-release.apk')"
#      - name: Previous output
#        run: |
#          echo "${{ steps.output.outputs.apkPath }}"

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: true
#          prerelease: false
#      - name: Upload Demo APK
#        id: upload_demo_apk
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          asset_path: ./app/build/outputs/apk/**/CircularSeekBar-demo-*-release.apk
#          asset_name: CircularSeekBar-demo.apk
#          asset_content_type: application/zip

#  release-library:
#    name: Release library to Sonatype maven repository
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Build library
#        run: |
#          ./gradlew clean uploadArchives --stacktrace
#        env:
#          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
#          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
